### ISSUE TITLE
not all games listed

### ISSUE THREAD

**Issue by bishonen** [scttcper/honbot-api#5]
Hey there, tremendous site you've put up. Any idea why there is only a subset of all ranked games there? Using the api from the hon website (api.heroesofnewerth.com/match_history/all/nickname/testor3/?token=yourtoken), I do get games from 2011 for the user 'bishonen'. On honbot, I get only the last ~2 years. Thanks!

**Comment by scttcper** [comment]
it doesn't use player match history to load matches, also match data isn't available pre v4 anymore
