### ISSUE TITLE
Doesn't show latest matches

### ISSUE THREAD

**Issue by shtefcs** [scttcper/honbot-api#6]
Hey Scott, nice to meet you finally.

I just went to check my latest games on HonBot, but seems it doesn't show latest matches. The latest one is 13 days ago, and i am playing daily. 

You can see on screenshot: https://i.imgur.com/pgyTpdi.png

Peace,

**Comment by scttcper** [comment]
thx looks like its loading again

**Comment by shtefcs** [comment]
its still says last match played 3days ago https://honbot.com/player/kinderjaje_ 

Is that how it should work? As far I remember it was showing very updated version before.
